# Definition of Spring Cloud Function that handles the Responsibility of the Event Processor
# Spring Cloud Binding for the Function in and out destination topics
# Spring Cloud Kafka Function binding of Consumer value Deserialization Configuration
# Spring Cloud Kafka Function binding of Producer value Deserialization Configuration
# Key Serializer and Deserializer are considered to be the default org.apache.kafka.common.serialization.StringSerializer
# Kafka Broker Binding defined for a Single Broker Environment that can be increased as per Brokers increment in any env

spring.cloud.stream:
  function:
    definition: filterActiveMessages
  bindings:
    filterActiveMessages-in-0:
      destination: kafka-stream-topic
    filterActiveMessages-out-0:
      destination: kafka-active-stream-topic
  kafka:
    bindings:
      filterActiveMessages-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      filterActiveMessages-out-0:
        producer:
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
    binder:
      brokers:
        - localhost:9092
